export const config = {
  MIN_PROCESS_REQUESTS: 1070,
  MAX_PROCESS_REQUESTS: 1570,
  MIN_PAGE_TABLE_SIZE: 34,
  MAX_PAGE_TABLE_SIZE: 54,
  MIN_MEMORY_REQUESTS: 34,
  MAX_MEMORY_REQUESTS: 54,
  WORKING_SET_REGENERATION_PROBABILITY: 5,
  NEW_PROCESS_CREATION_PROBABILITY: 20,
  TOTAL_PHYSICAL_PAGES: 100,
  INITIAL_PROCESS_COUNT: 4,
  MAX_RUNNING_PROCESSES: 15,
  PAGE_STAT_UPDATE_INTERVAL: 20,
  WS_CLOCK_TAU_MS: 20,
  DISABLE_LOGGING: false,
  USING_RANDOM_ALGORITHM:true,
  INTERVAL_MS:100
}
